# Generated by Django 5.0.3 on 2024-03-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weCureIt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="patientcreditcard",
            name="card_number",
            field=models.CharField(max_length=19, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="patientcreditcard",
            name="cvv",
            field=models.IntegerField(),
        ),
    ]
