# Generated by Django 5.0.3 on 2024-03-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "weCureIt",
            "0002_doctor_is_active_alter_patientcreditcard_card_number_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="address",
            new_name="addressLine1",
        ),
        migrations.RenameField(
            model_name="patientcreditcard",
            old_name="billing_address",
            new_name="addressLine1",
        ),
        migrations.AddField(
            model_name="patient",
            name="addressLine2",
            field=models.CharField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="patient",
            name="city",
            field=models.CharField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="patient",
            name="state",
            field=models.CharField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="patient",
            name="zipcode",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientcreditcard",
            name="addressLine2",
            field=models.CharField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="patientcreditcard",
            name="city",
            field=models.CharField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="patientcreditcard",
            name="state",
            field=models.CharField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="patientcreditcard",
            name="zipcode",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
