# Generated by Django 5.0.3 on 2024-03-31 00:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weCureIt", "0003_rename_address_patient_addressline1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="zipcode",
            new_name="zipCode",
        ),
        migrations.RenameField(
            model_name="patientcreditcard",
            old_name="zipcode",
            new_name="zipCode",
        ),
    ]
